# @package _global_

defaults:
  - override /dataset: openworld_text_contrastive
  - override /model: text_tuning
  - override /model/network/backbone: openclip_B_32
  - _self_

model:
  network:
    backbone:
      instance:
        _target_: models.networks.backbones.CLIPText
  optimizer:
    optim:
      lr: 0.0002
      weight_decay: 0.0001

is_baseline: false
class_name: city
text_tuning: True
max_epochs: 30
