# @package _global_

defaults:
  - override /dataset: openworld_contrastive
  - override /model: regression
  - override /model/network: contrastive_unfrozen_backbone
  - override /model/network/backbone: openclip_B_32
  - override /model/loss: contrastive
  - _self_

model:
  optimizer:
    optim:
      lr: 2e-4
      weight_decay: 0.0001
    backbone_lr: 2e-5

class_name: region
is_baseline: false
max_epochs: 30
