# @package _global_

defaults:
  - override /dataset: openworld_contrastive_best
  - override /model: hybrid
  - override /model/network: best_backbone
  - override /model/network/backbone: clip_L_14_DataComp
  - override /model/network/mid: mlp_hybrid
  - _self_

class_name: 'quadtree_10_1000'
is_baseline: false
max_epochs: 30
mode: 'eval'

model:
  name: best_model
  optimizer:
    optim:
      lr: 2e-4
      weight_decay: 0.0001
    backbone_lr: 2e-5
  network:
    head:
      instance:
        quadtree_path: ${root_dir}/quadtree_10_1000.csv

dataset:
  global_batch_size: 2048
