defaults:
  - model: default
  - computer: v100
  - dataset: openworld
  - _self_
  - exp: ???

model:
  val_metrics:
    _target_: metrics.distance_based.HaversineMetrics
    acc_radiuses:
      - 1
      - 25
      - 200
      - 750
      - 2500
    acc_area: []
    aux_data: ${aux_data}
  test_metrics:
    _target_: metrics.distance_based.HaversineMetrics
    acc_radiuses:
      - 1
      - 25
      - 200
      - 750
      - 2500
    acc_area: ${areas}
    aux_data: ${aux_data}
datamodule:
  _target_: data.datamodule.ImageDataModule
  train_dataset: ${dataset.train_dataset}
  val_dataset: ${dataset.val_dataset}
  test_dataset: ${dataset.test_dataset}
  global_batch_size: ${dataset.global_batch_size}
  num_workers: ${computer.num_workers}
  num_nodes: ${computer.num_nodes}
  num_devices: ${computer.devices}
  val_proportion: 0.1

trainer:
  _target_: pytorch_lightning.Trainer
  devices: ${computer.devices}
  accelerator: ${computer.accelerator}
  strategy: ${computer.strategy}
  num_nodes: ${computer.num_nodes}
  precision: ${computer.precision}
  max_epochs: ${max_epochs}

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: ${root_dir}
  name: ${experiment_name}
  project: plonk
  log_model: False
  offline: False
  entity: imaginelab

checkpoints:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${root_dir}/checkpoints/${experiment_name}
  filename: 'epoch_{epoch}'
  monitor: val/loss
  save_last: True
  save_top_k: 0
  every_n_epochs: 1

progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: ${computer.progress_bar_refresh_rate}

aux_data: []
max_epochs: 100
data_dir: ${root_dir}/datasets
root_dir:  ${hydra:runtime.cwd}
experiment_name: ${dataset.name}__${model.name}
mode: train # change that to eval to do the testing
num_classes: 0
areas: ['country', 'region', 'sub-region', 'city']
class_name: null
streetclip: False
blur: False
text_tuning: False

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/${experiment_name}
  job:
    chdir: true
