dataset:
  name: yfcc4k
  global_batch_size: 512
  test_dataset:
    _partial_: true
    _target_: data.data.Baseline
    path: ${data_dir}/baselines/yfcc4k
    which: 'yfcc4k'
    transforms: ${dataset.test_transform}
datamodule:
  _target_: data.datamodule.BaselineDataModule
  test_dataset: ${dataset.test_dataset}
  global_batch_size: ${dataset.global_batch_size}
  num_workers: ${computer.num_workers}
  num_nodes: ${computer.num_nodes}
  num_devices: ${computer.devices}
